<?php
/**
 * @file
 * views_slideshow_liquid_slider.module
 */

/**
 * Implements hook_libraries_info().
 */
function views_slideshow_liquid_slider_libraries_info() {
  $libraries['liquidslider'] = array(
    'name' => 'jQuery Liquid Slider',
    'vendor url' => 'http://liquidslider.kevinbatdorf.com/',
    'download url' => 'https://github.com/KevinBatdorf/liquidslider/zipball/master',
    'version arguments' => array(
      // 'pattern' => '@Version ([1-9].[0-9].+)@',
      'pattern' => '@([0-9]\.[0-9]\.[0-9])@',
      'file' => 'js/jquery.liquid-slider.js',
    ),
    'files' => array(
      'js' => array(
        'js/jquery.liquid-slider.js',
      ),
    ),
    'variants' => array(
      'minified' => array(
        'files' => array(
          'js' => array(
            'js/jquery.liquid-slider.min.js',
          ),
        ),
      ),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_theme().
 */
function views_slideshow_liquid_slider_theme($existing, $type, $theme, $path) {
  return array(
    'views_slideshow_liquid_slider_main_frame' => array(
      'variables' => array(
        'view' => NULL,
        'settings' => array(),
        'rows' => array(),
        'title' => '',
      ),
      'template' => 'theme/views-slideshow-liquidslider-main-frame',
      'file' => 'theme/views_slideshow_liquid_slider.theme.inc',
    ),
  );
}

/**
 * Implements hook_jqmulti_files().
 *
 * Add files to be loaded with jQuery Multi's jQuery library
 * @return
 *   An array of full paths to files that should be loaded with the jqmulti's jQuery library
 *   (paths are relative to Drupal root)
 */
function views_slideshow_liquid_slider_jqmulti_files() {
  $library_path = libraries_get_path('liquidslider');
  $module_path = drupal_get_path('module', 'views_slideshow_liquid_slider');
  return array(
    $library_path . '/js/jquery.easing.1.3.js',
    $library_path . '/js/jquery.touchSwipe.min.js',
    $library_path . '/js/jquery.liquid-slider.min.js',
    $module_path . '/js/liquidslider.js',
  );
}


/**
 * Gets the path to the Liquid Slider library.
 *
 * @return bool
 *   The path to the Liquid Slider library js file, or FALSE if not found.
 */
function _views_slideshow_liquid_slider_library_path() {
  // Add support for Libraries 2.x.
  if (function_exists('libraries_load')) {
    if (($library = libraries_load('liquidslider', 'minified')) && $library['installed']) {
      return TRUE;
    }
    else {
      return FALSE;
    }
  }

  // Legacy code to support Libraries 1.x until Libraries 2.x
  // has a stable release.
  $library_path = libraries_get_path('liquidslider');

  if (!empty($library_path)) {
    // Attempt to use mini, 'minified'fied version of Liquid Slider plugin.
    if (file_exists($liquidslider_path = $library_path . '/js/jquery.liquid-slider.min.js')) {
      return $liquidslider_path;
    }
    // Otherwise use non-minified version if available.
    elseif (file_exists($liquidslider_path = $library_path . '/js/jquery.liquid-slider.js')) {
      return $liquidslider_path;
    }
  }

  return FALSE;
}

/**
 * Get the install error message.
 */
function _views_slideshow_liquid_slider_get_install_error_message() {
  $library_path = 'sites/all/libraries/';
  //libraries_get_path('liquidslider');
  $library_url = 'https://github.com/KevinBatdorf/liquidslider/zipball/master';
  $library_link = l($library_url, $library_url,
    array('attributes' => array('target' => '_blank')));

  $t = get_t();
  $output = $t('The jQuery Liquid Slider plugin needs to be installed.');
  $output .= ' ';
  $output .= $t('Download the jQuery plugin from !link and unzip it into @library_path',
    array(
      '!link' => $library_link,
      '@library_path' => $library_path,
    )
  );
  $output .= '<br>';
  $output .= '<b>CAUTION:</b> You must rename the folder name "liquidslider-master" to "liquidslider"';
   return $output;
}
