; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc4"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.3"

projects[less][subdir] = "contrib"
projects[less][version] = "3.0"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.1"

; Themes
projects[bootstrap][version] = "3.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[lavender][download][type] = ""
projects[lavender][download][url] = ""
projects[lavender][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery][download][type] = ""
libraries[jquery][download][url] = ""
libraries[jquery][directory_name] = "jquery"
libraries[jquery][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[lessphp][download][type] = ""
libraries[lessphp][download][url] = ""
libraries[lessphp][directory_name] = "lessphp"
libraries[lessphp][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[old-lessphp][download][type] = ""
libraries[old-lessphp][download][url] = ""
libraries[old-lessphp][directory_name] = "old-lessphp"
libraries[old-lessphp][type] = "library"

